certmaster returns None for minion only setups with commit f6ee54c2457bec39c869d9526d47e977e87c702c. So use that return value to determine minion only setups to solve following exception;
2010-07-19 18:21:24,406 - ERROR - Exception occured: <type 'exceptions.IOError'>
Traceback (most recent call last):
 File "/usr/lib/python2.5/site-packages/func/minion/server.py", line 196, in __call__
   rc = self.__method(*args)
 File "/usr/lib/python2.5/site-packages/func/minion/modules/func_module.py", line 43, in wrapper
   return fn(*args)
 File "/usr/lib/python2.5/site-packages/func/minion/modules/overlord.py", line 36, in map_minions
   cm = certmaster.CertMaster()
 File "/usr/lib/python2.5/site-packages/certmaster/certmaster.py", line 79, in __init__
   self.cacert = certs.retrieve_cert_from_file(self.ca_cert_file)
 File "/usr/lib/python2.5/site-packages/certmaster/certs.py", line 86, in retrieve_cert_from_file
   fo = open(certfile, 'r')
IOError: [Errno 2] No such file or directory: '/etc/pki/certmaster/ca/certmaster.crt'