Exclude down hosts otherwise func "*" ping command causes following error;
[ ok ... ] planetlab...
[ ok ... ] planetlab...
[ ok ... ] 147-179...
ERROR: Can't find any minions matching "planetlab-2.iscte.pt".
[root@www /]# grep planetlab-2.iscte.pt /var/lib/func/hosts_down.lst
planetlab-2.iscte.pt